export const studentFeatures = [
  'Attendance Overview',
  'Subject-wise Marks',
  'Timetable',
  'Assignments Tracker',
  'Submission Status',
  'Digital Materials',
  'Exam Schedule',
  'Fee Status',
  'Payment History',
  'Transport Tracking',
  'Library Account',
  'Lab Bookings',
  'Hostel Information',
  'Scholarship Status',
  'Counselling Slot',
  'Mentor Connect',
  'Doubt Support Chatbot',
  'Class Announcements',
  'Academic Calendar',
  'Hall Ticket Download',
  'Progress Card',
  'Club Enrollment',
  'Certificate Requests',
  'Profile Settings',
  'Complaint Box',
  'Student IDs',
  'Student Academy',
  'JEE Mains Prep',
  'NEET Prep',
  'MPC Courses',
  'BIPC Courses',
  'MBIPC Courses',
  'Weekly Exams',
  'References Hub',
  'Sections Planner',
]

export const facultyFeatures = [
  'Attendance Entry',
  'Marks Entry',
  'Assignment Creator',
  'Question Bank Upload',
  'Lesson Planner',
  'Class Timetable',
  'Department Notices',
  'Syllabus Tracker',
  'Student Feedback',
  'Parent Messaging',
  'Mentoring Log',
  'Research Tracker',
  'Leave Application',
  'Resource Repository',
  'Exam Invigilation',
  'Counselling Notes',
  'Academic Analytics',
  'Remedial Classes',
  'Performance Alerts',
  'Fee Defaulter View',
  'Event Coordination',
  'Project Evaluation',
  'Chat & Broadcast',
  'Profile Settings',
  'Grievance Forwarding',
]

export const parentFeatures = [
  'Child Attendance',
  'Marks Progress',
  'Fee Dashboard',
  'Due Alerts',
  'PTM Booking',
  'Teacher Communication',
  'Bus Tracking',
  'Daily Homework',
  'Exam Calendar',
  'Discipline Alerts',
  'Health Records',
  'Leave Requests',
  'Parent Notices',
  'Library Summary',
  'Performance Charts',
  'Scholarship View',
  'Hostel Updates',
  'Emergency Contact',
  'Digital Consent Forms',
  'Profile Settings',
]

export const adminFeatures = [
  'Student Management',
  'Faculty Management',
  'Parent Accounts',
  'Admissions Pipeline',
  'Fee Collection',
  'Fee Concessions',
  'Transport Routes',
  'Hostel Allocation',
  'Attendance Audit',
  'Exam Setup',
  'Result Publishing',
  'Timetable Generation',
  'Department Config',
  'Role Permissions',
  'Payroll Preview',
  'Leave Approvals',
  'Asset Inventory',
  'Library Operations',
  'Event Management',
  'Circular Broadcast',
  'Website Notices',
  'Document Templates',
  'Compliance Reports',
  'Analytics Center',
  'SMS Gateway UI',
  'Email Gateway UI',
  'Helpdesk Console',
  'Backup Management',
  'Backup Status',
  'Backup Export',
  'Restore Points',
  'System Health',
  'Audit Logs',
]
