import { useState, useEffect } from 'react'
import { useParams } from 'react-router-dom'
import { getApiBaseURL } from '../../config/apiConfig'

export default function PublicReportViewer() {
  const { token } = useParams()
  const [report, setReport] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  useEffect(() => {
    async function loadReport() {
      try {
        setLoading(true)
        const res = await fetch(`${getApiBaseURL()}/v1/reports/token/${token}`)
        if (!res.ok) {
          throw new Error('Report not found or link has expired.')
        }
        const data = await res.json()
        setReport(data)
      } catch (err) {
        setError(err.message || 'Failed to load report')
      } finally {
        setLoading(false)
      }
    }
    if (token) {
      loadReport()
    }
  }, [token])

  if (loading) {
    return (
      <div style={{ minHeight: '80vh', display: 'flex', alignItems: 'center', justifyContent: 'center', color: '#64748b' }}>
        <p>Verifying secure report authorization & loading document...</p>
      </div>
    )
  }

  if (error || !report) {
    return (
      <div style={{ minHeight: '80vh', display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', textAlign: 'center', padding: '2rem' }}>
        <h2 style={{ color: '#EF4444' }}>Report Unavailable</h2>
        <p style={{ color: '#64748b', maxWidth: '400px' }}>{error || 'This report link is invalid or no longer active.'}</p>
        <a href="/" className="btn btn-primary" style={{ marginTop: '1rem' }}>
          Return to EduFlow Home
        </a>
      </div>
    )
  }

  return (
    <div style={{ background: '#0f172a', minHeight: '100vh', color: '#f8fafc', padding: '2.5rem 1rem' }}>
      <div
        style={{
          maxWidth: '860px',
          margin: '0 auto',
          background: '#1e293b',
          borderRadius: '1rem',
          border: '1px solid #334155',
          padding: '2.5rem',
          boxShadow: '0 10px 25px rgba(0,0,0,0.3)',
        }}
      >
        <span
          style={{
            display: 'inline-block',
            background: '#2563eb',
            color: '#fff',
            padding: '0.25rem 0.75rem',
            borderRadius: '999px',
            fontSize: '0.8rem',
            fontWeight: 700,
            marginBottom: '1rem',
          }}
        >
          {report.report_type}
        </span>
        <h1 style={{ fontSize: '1.8rem', margin: '0 0 0.5rem 0', color: '#ffffff' }}>
          {report.title}
        </h1>
        <div
          style={{
            color: '#94a3b8',
            fontSize: '0.9rem',
            marginBottom: '2rem',
            borderBottom: '1px solid #334155',
            paddingBottom: '1rem',
          }}
        >
          <strong>Institution:</strong> {report.college_name} &bull;{' '}
          <strong>Views:</strong> {report.views_count} &bull;{' '}
          <strong>Generated:</strong> {new Date(report.created_at).toLocaleDateString('en-IN')}
        </div>

        <div
          style={{
            background: '#0b132b',
            border: '1px solid #1e293b',
            borderRadius: '0.75rem',
            padding: '1.5rem',
            lineHeight: 1.7,
            fontSize: '0.95rem',
            color: '#e2e8f0',
            whiteSpace: 'pre-line',
          }}
        >
          {report.report_content}
        </div>

        <div
          style={{
            marginTop: '2rem',
            display: 'flex',
            justifyContent: 'space-between',
            alignItems: 'center',
            flexWrap: 'wrap',
            gap: '1rem',
          }}
        >
          <a
            href={`${getApiBaseURL()}/v1/reports/download/${token}`}
            className="btn btn-primary"
            style={{ fontWeight: 700, padding: '0.6rem 1.5rem' }}
          >
            📥 Download Official PDF
          </a>
          <button
            onClick={() => window.print()}
            className="btn btn-secondary"
            style={{ fontWeight: 700, padding: '0.6rem 1.5rem', background: '#334155', border: 'none' }}
          >
            🖨️ Print Report
          </button>
        </div>

        <div style={{ marginTop: '2.5rem', textAlign: 'center', fontSize: '0.8rem', color: '#64748b' }}>
          Generated by EduFlow AI OS &bull; Confidential Institutional Document
        </div>
      </div>
    </div>
  )
}
