/**
 * Controller for exporting AI Officer reports as branded PDF documents.
 */
import { logger } from '../utils/logger.js'

function escapePdfText(str) {
  if (!str) return ''
  return str
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
}

function generatePdfBuffer({ title, institutionName, text, officerType }) {
  const institution = institutionName || 'Sri Siddhartha Institute of Technology'
  const lines = (text || '').split('\n')
  const timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })

  let streamContent = 'BT\n'

  // Header Banner Text
  streamContent += `/F1 18 Tf\n50 740 Td\n(${escapePdfText(institution)}) Tj\n`
  streamContent += `/F1 13 Tf\n0 -22 Td\n(${escapePdfText(title)}) Tj\n`
  streamContent += `/F2 9 Tf\n0 -16 Td\n(Generated by EduFlow AI OS - Officer: ${escapePdfText(officerType)} - ${escapePdfText(timestamp)}) Tj\n`

  streamContent += 'ET\n'

  // Divider Line
  streamContent += 'q 0.05 0.6 0.8 rg 50 686 512 2 re f Q\n'

  // Body content
  streamContent += 'BT\n/F2 10 Tf\n50 665 Td\n15 TL\n'

  let y = 665
  for (const rawLine of lines) {
    const cleanLine = rawLine
      .replace(/[#*`_]/g, '')
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
      .trim()

    if (!cleanLine) {
      streamContent += 'T*\n'
      y -= 15
    } else {
      // Wrap lines longer than 85 chars
      const chunks = cleanLine.match(/.{1,85}(\s|$)/g) || [cleanLine]
      for (const chunk of chunks) {
        streamContent += `(${escapePdfText(chunk.trim())}) Tj T*\n`
        y -= 15
        if (y < 60) break
      }
    }
    if (y < 60) break
  }

  // Footer text
  if (y >= 45) {
    streamContent += `ET\nq 0.6 0.6 0.6 rg 50 42 512 1 re f Q\nBT\n/F2 8 Tf\n50 30 Td\n(EduFlow AI OS Institutional Intelligence Platform - Confidential Report) Tj\nET\n`
  } else {
    streamContent += 'ET\n'
  }

  const streamLen = Buffer.byteLength(streamContent, 'utf-8')

  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>\nendobj',
    `4 0 obj\n<< /Length ${streamLen} >>\nstream\n${streamContent}endstream\nendobj`,
    '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj',
    '6 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj',
  ]

  let pdf = '%PDF-1.4\n'
  const offsets = []
  for (const obj of objects) {
    offsets.push(Buffer.byteLength(pdf, 'utf-8'))
    pdf += obj + '\n'
  }

  const xrefOffset = Buffer.byteLength(pdf, 'utf-8')
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  for (const off of offsets) {
    pdf += `${String(off).padStart(10, '0')} 00000 n \n`
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`

  return Buffer.from(pdf, 'utf-8')
}

export class OfficerExportController {
  static async exportPdf(req, res) {
    try {
      const { type } = req.params
      const validTypes = ['accreditation', 'student-success', 'timetable', 'admissions', 'finance']
      if (!validTypes.includes(type)) {
        return res.status(400).json({ error: `Invalid officer type: ${type}` })
      }

      const { text = '', institutionName } = req.body

      const officerTitles = {
        accreditation: 'AI Accreditation & NAAC/NBA Compliance Report',
        'student-success': 'AI Student Success & Dropout Risk Report',
        timetable: 'AI Academic Timetable & Scheduling Optimization',
        admissions: 'AI Admissions Yield & Conversion Analysis',
        finance: 'AI Financial Fee Reconciliation Audit',
      }

      const title = officerTitles[type] || `AI ${type} Officer Report`
      const pdfBuffer = generatePdfBuffer({
        title,
        institutionName,
        text,
        officerType: type,
      })

      const filename = `eduflow-${type}-report-${Date.now()}.pdf`
      res.setHeader('Content-Type', 'application/pdf')
      res.setHeader('Content-Disposition', `attachment; filename="${filename}"`)
      res.setHeader('Content-Length', pdfBuffer.length)

      return res.end(pdfBuffer)
    } catch (err) {
      logger.error('PDF export error:', err)
      return res.status(500).json({ error: 'Failed to generate PDF export' })
    }
  }
}
