import crypto from 'crypto'
import { z } from 'zod'
import { ReportDeliveryRepository } from '../models/ReportDeliveryRepository.js'
import { LeadRepository } from '../models/LeadRepository.js'
import { sendEmail } from '../services/email/emailService.js'
import { logger } from '../utils/logger.js'

function escapePdfText(str) {
  if (!str) return ''
  return str
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
}

export function generateReportPdfBuffer({ title, collegeName, reportContent, reportType }) {
  const institution = collegeName || 'Educational Institution'
  const lines = (reportContent || '').split('\n')
  const timestamp = new Date().toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })

  let streamContent = 'BT\n'

  // Header Banner Text
  streamContent += `/F1 18 Tf\n50 740 Td\n(${escapePdfText(institution)}) Tj\n`
  streamContent += `/F1 13 Tf\n0 -22 Td\n(${escapePdfText(title || 'Accreditation Audit Report')}) Tj\n`
  streamContent += `/F2 9 Tf\n0 -16 Td\n(Report Type: ${escapePdfText(reportType || 'NAAC Audit')} - Generated by EduFlow AI OS - ${escapePdfText(timestamp)}) Tj\n`
  streamContent += 'ET\n'

  // Divider Line
  streamContent += 'q 0.05 0.6 0.8 rg 50 686 512 2 re f Q\n'

  // Body content
  streamContent += 'BT\n/F2 10 Tf\n50 665 Td\n15 TL\n'

  let y = 665
  for (const rawLine of lines) {
    const cleanLine = rawLine
      .replace(/[#*`_]/g, '')
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
      .trim()

    if (!cleanLine) {
      streamContent += 'T*\n'
      y -= 15
    } else {
      const chunks = cleanLine.match(/.{1,85}(\s|$)/g) || [cleanLine]
      for (const chunk of chunks) {
        streamContent += `(${escapePdfText(chunk.trim())}) Tj T*\n`
        y -= 15
        if (y < 60) break
      }
    }
    if (y < 60) break
  }

  // Footer text
  if (y >= 45) {
    streamContent += `ET\nq 0.6 0.6 0.6 rg 50 42 512 1 re f Q\nBT\n/F2 8 Tf\n50 30 Td\n(EduFlow AI OS Accreditation Platform - Confidential Institutional Report) Tj\nET\n`
  } else {
    streamContent += 'ET\n'
  }

  const streamLen = Buffer.byteLength(streamContent, 'utf-8')

  const objects = [
    '1 0 obj\n<< /Type /Catalog /Pages 2 0 R >>\nendobj',
    '2 0 obj\n<< /Type /Pages /Kids [3 0 R] /Count 1 >>\nendobj',
    '3 0 obj\n<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Contents 4 0 R /Resources << /Font << /F1 5 0 R /F2 6 0 R >> >> >>\nendobj',
    `4 0 obj\n<< /Length ${streamLen} >>\nstream\n${streamContent}endstream\nendobj`,
    '5 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>\nendobj',
    '6 0 obj\n<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>\nendobj',
  ]

  let pdf = '%PDF-1.4\n'
  const offsets = []
  for (const obj of objects) {
    offsets.push(Buffer.byteLength(pdf, 'utf-8'))
    pdf += obj + '\n'
  }

  const xrefOffset = Buffer.byteLength(pdf, 'utf-8')
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`
  for (const off of offsets) {
    pdf += `${String(off).padStart(10, '0')} 00000 n \n`
  }
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`

  return Buffer.from(pdf, 'utf-8')
}

const deliverSchema = z.object({
  leadId: z.number().optional().nullable(),
  collegeName: z.string().min(1, 'College name is required'),
  contactEmail: z.string().email('Valid recipient email is required'),
  reportType: z.string().optional().default('NAAC_EXECUTIVE_SUMMARY'),
  title: z.string().optional().default('Accreditation Audit Report'),
  reportContent: z.string().min(1, 'Report content is required'),
  criteriaScores: z.record(z.any()).optional(),
})

export class ReportDeliveryController {
  static async deliverReport(req, res) {
    try {
      const parsed = deliverSchema.safeParse(req.body)
      if (!parsed.success) {
        return res.status(400).json({ error: 'Validation failed', details: parsed.error.errors })
      }

      const { leadId, collegeName, contactEmail, reportType, title, reportContent, criteriaScores } = parsed.data
      const token = crypto.randomBytes(16).toString('hex')

      const delivered = await ReportDeliveryRepository.create({
        leadId,
        token,
        collegeName,
        contactEmail,
        reportType,
        title,
        reportContent,
        criteriaScores: criteriaScores || {},
      })

      // If leadId was provided, update lead status to PILOT_DELIVERED
      if (leadId) {
        await LeadRepository.update(leadId, {
          status: 'PILOT_DELIVERED',
          notes: `[${new Date().toISOString()}] Report delivered via token ${token}`,
        }).catch((err) => logger.warn(`Could not update lead ${leadId}: ${err.message}`))
      }

      const publicBaseUrl = process.env.APP_PUBLIC_URL || 'http://localhost:5173'
      const viewUrl = `${publicBaseUrl}/r/${token}`
      const directPdfUrl = `${publicBaseUrl}/r/${token}/pdf`

      // Dispatch Email with report link
      await sendEmail({
        to: contactEmail,
        subject: `[EduFlow] Your Accreditation Report for ${collegeName} is Ready`,
        html: `
          <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 24px; color: #1e293b;">
            <h2 style="color: #2563EB;">EduFlow AI OS &bull; Accreditation Intelligence</h2>
            <p>Dear Administrator,</p>
            <p>Your institutional report for <strong>${collegeName}</strong> has been generated and is now ready for your review.</p>
            <div style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 8px; padding: 16px; margin: 20px 0;">
              <p style="margin: 0 0 8px 0;"><strong>Report:</strong> ${title}</p>
              <p style="margin: 0 0 8px 0;"><strong>Type:</strong> ${reportType}</p>
              <p style="margin: 0;"><strong>Delivered on:</strong> ${new Date().toLocaleDateString('en-IN')}</p>
            </div>
            <p style="margin: 28px 0;">
              <a href="${viewUrl}" style="background: #2563EB; color: white; padding: 12px 24px; border-radius: 6px; text-decoration: none; font-weight: bold; display: inline-block;">
                View Secure Report Online &rarr;
              </a>
            </p>
            <p style="font-size: 13px; color: #64748b;">
              Direct link: <a href="${viewUrl}">${viewUrl}</a>
            </p>
            <hr style="border: none; border-top: 1px solid #e2e8f0; margin: 28px 0;" />
            <p style="font-size: 12px; color: #94a3b8;">
              This is a confidential report generated by EduFlow AI OS. If you have any questions, reply directly to this email.
            </p>
          </div>
        `,
      }).catch((err) => logger.warn(`Failed to dispatch report delivery email: ${err.message}`))

      return res.status(201).json({
        success: true,
        message: 'Report delivered successfully',
        report: delivered,
        viewUrl,
        directPdfUrl,
      })
    } catch (err) {
      logger.error('Error delivering report:', err)
      return res.status(500).json({ error: 'Failed to deliver report' })
    }
  }

  static async getDeliveredReports(req, res) {
    try {
      const page = parseInt(req.query.page, 10) || 1
      const limit = parseInt(req.query.limit, 10) || 50
      const result = await ReportDeliveryRepository.findAll({ page, limit })
      return res.json(result)
    } catch (err) {
      logger.error('Error fetching delivered reports:', err)
      return res.status(500).json({ error: 'Failed to load delivered reports' })
    }
  }

  static async getReportByToken(req, res) {
    try {
      const { token } = req.params
      const report = await ReportDeliveryRepository.incrementViews(token)
      if (!report) {
        return res.status(404).json({ error: 'Report not found or link expired' })
      }
      return res.json(report)
    } catch (err) {
      logger.error('Error retrieving report by token:', err)
      return res.status(500).json({ error: 'Failed to load report' })
    }
  }

  static async downloadPublicReportPdf(req, res) {
    try {
      const { token } = req.params
      const report = await ReportDeliveryRepository.findByToken(token)
      if (!report) {
        return res.status(404).send('Report not found')
      }

      const pdfBuffer = generateReportPdfBuffer({
        title: report.title,
        collegeName: report.college_name,
        reportContent: report.report_content,
        reportType: report.report_type,
      })

      const filename = `${report.college_name.replace(/[^a-zA-Z0-9]/g, '_')}_Report.pdf`
      res.setHeader('Content-Type', 'application/pdf')
      res.setHeader('Content-Disposition', `attachment; filename="${filename}"`)
      return res.send(pdfBuffer)
    } catch (err) {
      logger.error('Error downloading report PDF:', err)
      return res.status(500).send('Failed to generate PDF')
    }
  }

  static async renderPublicReportHtml(req, res) {
    try {
      const { token } = req.params
      const report = await ReportDeliveryRepository.incrementViews(token)
      if (!report) {
        return res.status(404).send(`
          <!DOCTYPE html>
          <html>
            <head><title>Report Not Found - EduFlow</title></head>
            <body style="font-family: sans-serif; text-align: center; padding: 50px;">
              <h1>404 - Report Not Found</h1>
              <p>The requested report link is invalid or has expired.</p>
            </body>
          </html>
        `)
      }

      const safeCollege = report.college_name.replace(/</g, '&lt;').replace(/>/g, '&gt;')
      const safeTitle = report.title.replace(/</g, '&lt;').replace(/>/g, '&gt;')
      const safeContent = (report.report_content || '')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/\n/g, '<br/>')

      const html = `
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>${safeTitle} - ${safeCollege} | EduFlow</title>
          <style>
            body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #0f172a; color: #f8fafc; margin: 0; padding: 2rem 1rem; }
            .container { max-width: 860px; margin: 0 auto; background: #1e293b; border-radius: 1rem; border: 1px solid #334155; padding: 2.5rem; box-shadow: 0 10px 25px rgba(0,0,0,0.3); }
            .badge { display: inline-block; background: #2563eb; color: #fff; padding: 0.25rem 0.75rem; border-radius: 999px; font-size: 0.8rem; font-weight: 700; margin-bottom: 1rem; }
            h1 { font-size: 1.8rem; margin: 0 0 0.5rem 0; color: #ffffff; }
            .meta { color: #94a3b8; font-size: 0.9rem; margin-bottom: 2rem; border-bottom: 1px solid #334155; padding-bottom: 1rem; }
            .content-box { background: #0b132b; border: 1px solid #1e293b; border-radius: 0.75rem; padding: 1.5rem; line-height: 1.7; font-size: 0.95rem; color: #e2e8f0; white-space: normal; }
            .actions { margin-top: 2rem; display: flex; justify-content: space-between; align-items: center; flex-wrap: wrap; gap: 1rem; }
            .btn { background: #2563eb; color: white; padding: 0.75rem 1.5rem; border-radius: 0.5rem; text-decoration: none; font-weight: 700; display: inline-block; border: none; cursor: pointer; }
            .btn:hover { background: #1d4ed8; }
            .footer { margin-top: 2rem; text-align: center; font-size: 0.8rem; color: #64748b; }
            @media print {
              body { background: white; color: black; padding: 0; }
              .container { border: none; box-shadow: none; padding: 0; max-width: 100%; background: white; color: black; }
              .content-box { background: white; color: black; border: none; padding: 0; }
              .actions { display: none; }
            }
          </style>
        </head>
        <body>
          <div class="container">
            <span class="badge">${report.report_type}</span>
            <h1>${safeTitle}</h1>
            <div class="meta">
              <strong>Institution:</strong> ${safeCollege} &bull; 
              <strong>Views:</strong> ${report.views_count} &bull; 
              <strong>Generated:</strong> ${new Date(report.created_at).toLocaleDateString('en-IN')}
            </div>
            <div class="content-box">
              ${safeContent}
            </div>
            <div class="actions">
              <a href="/r/${token}/pdf" class="btn">📥 Download Official PDF</a>
              <button onclick="window.print()" class="btn" style="background: #334155;">🖨️ Print Report</button>
            </div>
            <div class="footer">
              Generated by EduFlow AI OS &bull; Confidential Institutional Document
            </div>
          </div>
        </body>
        </html>
      `
      res.setHeader('Content-Type', 'text/html')
      return res.send(html)
    } catch (err) {
      logger.error('Error rendering public report html:', err)
      return res.status(500).send('Internal Server Error')
    }
  }
}

export default ReportDeliveryController
